# Generated by Django 2.2 on 2020-08-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200804_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='appartment_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
